source 'https://rubygems.org'

gem 'sinatra', '~> 1.3.4'
gem 'sinatra-contrib', '~> 1.3.2'
gem 'json',  '~> 1.7.7'
gem 'dm-core', '~> 1.2.0'
gem 'dm-sqlite-adapter'
gem 'dm-validations'
gem 'dm-timestamps'
gem 'dm-migrations'
gem 'debugger'